version: '3.4'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: Biginit12345
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  web:
     build: .
     ports:
        - "8000:80"
        - "44348:443"
     volumes:
         - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
         - ${HOME}/.aspnet/https:/root/.aspnet/https/
     depends_on:
         - mongo
     links:
         - mongo
volumes:
  mongodb_data:
    external: true